# SPDX-License-Identifier: MIT
name: 'Extract Release Notes'
author: 'Felix Furrer'
description: 'Extract release notes from a "Keep a Changelog" changelog file.'
branding:
  icon: 'align-left'
  color: 'white'
inputs:
  changelog_file:
    description: 'The input path of the changelog file.'
    required: false
    default: 'CHANGELOG.md'
  release_notes_file:
    description: 'The output path of the (optional) release notes file.'
    required: false
outputs:
  release_notes:
    description: 'The escaped release notes.'
runs:
  using: 'node12'
  main: 'dist/index.js'
