# SPDX-License-Identifier: MIT
name: 'Extract Release Notes'
description: 'Extract release notes from a "Keep a Changelog" changelog file.'
author: 'Felix Furrer'
branding:
  icon: 'align-left'
  color: 'white'
inputs:
  changelog_file:
    description: 'The input path of the changelog file. Default: `CHANGELOG.md`'
    required: false
    default: 'CHANGELOG.md'
  release_notes_file:
    description: 'The output path of the release notes file (optional).'
    required: false
  prerelease:
    description: '`true` to get release notes from the `[Unreleased]` section. `false` to get release notes for the latest release. Default: `false`'
    required: false
    default: 'false'
  version_prefix:
    description: 'A prefix before the version number in the changelog.md header tag, e.g. `version` as in [version x.y.z]. Default: ``'
    required: false
    default: ''
  header_level:
    description: 'The header level where the version description is expected. Default: `2`'
    required: false
    default: 2
outputs:
  release_notes:
    description: 'The escaped release notes.'
runs:
  using: 'node20'
  main: 'dist/index.js'
