# SPDX-License-Identifier: MIT
name: 'Extract Release Notes'
description: 'Extract release notes from a "Keep a Changelog" changelog file.'
author: 'Felix Furrer'
branding:
  icon: 'align-left'
  color: 'white'
inputs:
  changelog_file:
    description: 'The input path of the changelog file. Default: `CHANGELOG.md`'
    required: false
    default: 'CHANGELOG.md'
  release_notes_file:
    description: 'The output path of the release notes file (optional).'
    required: false
  prerelease:
    description: '`true` to get release notes from the `[Unreleased]` section. `false` to get release notes for the latest release. Default: `false`'
    required: false
    default: 'false'
outputs:
  release_notes:
    description: 'The escaped release notes.'
runs:
  using: 'node20'
  main: 'dist/index.js'
