# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

includes:
  git: ./tasks/GitTasks.yml
  licensed: ./tasks/LicensedTasks.yml
  lint: ./tasks/LinterTasks.yml
  npm: ./tasks/NpmTasks.yml

vars:
  PROJECT_NAME: extract-release-notes

tasks:
  default:
    cmds:
    - task --list
    silent: true

  clean:
    desc: Delete build artifacts
    cmds:
    - task: npm:clean
    silent: true

  build:
    desc: Build {{.PROJECT_NAME}}
    cmds:
    - task: npm:build
    silent: true

  release:
    desc: Build release
    cmds:
    - task: npm:release
    - task: licensed:status
    silent: true

  lint:
    desc: Run all linters
    cmds:
    - task: lint:markdownlint
    - task: lint:yamllint
    silent: true

  version:
    desc: Show versions
    cmds:
    - |
      set -e
      printf 'git:      %s\n' "$(git --version | cut -d ' ' -f 3)"
      printf 'licensed: %s\n' "$(licensed version)"
      printf 'ncc:      %s\n' "$(ncc version)"
      printf 'node:     %s\n' "$(node --version | cut -c 2-)"
      printf 'npm:      %s\n' "$(npm --version)"
      printf 'task:     %s\n' "$(task --version | cut -d ' ' -f 3)"
      printf 'yamllint: %s\n' "$(yamllint --version | cut -d ' ' -f 2)"
    silent: true
