# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  list-tags:
    desc: List tags
    cmds:
    - git --no-pager tag -n
    silent: true

  list-remote-tags:
    desc: List remote tags
    cmds:
    - git --no-pager ls-remote --tags --refs origin
    silent: true

  fetch:
    desc: Fetch
    cmds:
    - git fetch --verbose --all --force --tags --prune --prune-tags
    silent: true

  create-tag:
    desc: Create release tag
    vars:
      GIT_TAG: '{{default .DOCKER_TAG .GIT_TAG}}'
    preconditions:
    - sh: '{{if empty .GIT_TAG}}false{{end}}'
      msg: 'error: variable "GIT_TAG" is required (e.g. task git:create-tag GIT_TAG=v0.0.0)'
    cmds:
    - git tag --annotate --message='release {{.GIT_TAG}}' --sign {{.GIT_TAG}}
    - task: list-tags
    silent: true

  push-tag:
    desc: Push release tag
    preconditions:
    - sh: '{{if empty .GIT_TAG}}false{{end}}'
      msg: 'error: variable "GIT_TAG" is required (e.g. task git:push-tag GIT_TAG=v0.0.0)'
    cmds:
    - git push origin {{.GIT_TAG}}
    - task: list-remote-tags
    silent: true
