# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  list:dependencies:
    desc: List dependencies
    cmds:
    - licensed list
    silent: true

  list:licenses:
    desc: List licenses
    dir: .licenses
    cmds:
    - |
      find . -name '*.yml' -type f -exec grep -h 'license: ' {} + | sed 's/^license: //' | sort -u
    silent: true

  status:
    desc: Check licensed status
    cmds:
    - licensed status
    silent: true

  cache:
    desc: Update licensed cache
    cmds:
    - npm ci
    - licensed cache --force
    silent: true

  notices:
    desc: Generate NOTICE file
    cmds:
    - licensed notices
    silent: true
