# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  fix-binary:
    desc: Delete the quarantine extended attribute
    cmds:
    - xattr -d com.apple.quarantine "${HOME}/.local/bin/licensed"
    silent: true

  list:
    desc: List dependencies
    cmds:
    - licensed list
    silent: true

  status:
    desc: Check licensed status
    cmds:
    - licensed status
    silent: true

  cache:
    desc: Upate licensed cache
    cmds:
    - npm ci
    - licensed cache --force
    silent: true

  notices:
    desc: Generate NOTICE file
    cmds:
    - licensed notices
    silent: true
