# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
    - rm -rf node_modules/
    silent: true

  install:
    desc: Install packages
    cmds:
    - npm install
    silent: true

  lint:
    desc: Lint code
    cmds:
    - npm run lint
    silent: true

  build:
    desc: Compile Node.js module
    preconditions:
    - sh: '[[ "$(node --version | cut -c 2-)" =~ "^20\.[[:digit:]]+\.[[:digit:]]+$" ]]'
      msg: 'error: unsupported Node.js version'
    cmds:
    - rm -rf dist/
    - task: install
    - task: lint
    - npm run package
    - git add dist/index.js
    silent: true

  release:
    desc: Compile Node.js module
    cmds:
    - rm -rf dist/
    - npm ci
    - npm run all
    - git add dist/*
    silent: true

  check-dependency-updates:
    desc: Check dependency updates
    cmds:
    - ncu
    silent: true

  update-dependencies:
    desc: Update dependency updates
    cmds:
    - ncu --upgrade
    silent: true
