---
ignore: |
  .git/
  .licenses/
  node_modules/

extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-values: enable
  indentation:
    spaces: 2
    indent-sequences: false
  line-length: disable
  quoted-strings:
    quote-type: single
    required: false
  truthy:
    allowed-values:
    - 'true'
    - 'false'
    - 'on'
