# SPDX-License-Identifier: MIT
name: yamllint

on:
  push:
    branches:
    - main
    paths:
    - '**.ya?ml'
  pull_request:
    branches:
    - main
    paths:
    - '**.ya?ml'

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    uses: ffurrer2/shared-workflows/.github/workflows/yamllint.yml@0cab87d07604b5d218ebc33a730bd079270eb3ca
